/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Forms.PatientForm;

/**
 *
 * @author jingxian
 */
public class ResetPassword extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResetPassword.class.getName());
    private boolean submitted = false;
    private String oldPassword;
    private String newPassword;
    private String confirmPassword;

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public boolean isSubmitted() {
        return submitted;
    }

    public String getOldPassword() {
        return oldPassword;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public String getConfirmPassword() {
        return confirmPassword;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        oldPasswordTf = new javax.swing.JPasswordField();
        newPasswordTf = new javax.swing.JPasswordField();
        confirmPasswordTf = new javax.swing.JPasswordField();
        resetBtn = new javax.swing.JButton();
        oldPasswordCb = new javax.swing.JCheckBox();
        newPasswordCb = new javax.swing.JCheckBox();
        confirmPasswordCb = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("Reset Password");
        jLabel12.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Old Password:");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setText("New Password:");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setText("Confirm Password:");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(this::resetBtnActionPerformed);

        oldPasswordCb.setText("show");
        oldPasswordCb.addActionListener(this::oldPasswordCbActionPerformed);

        newPasswordCb.setText("show");
        newPasswordCb.addActionListener(this::newPasswordCbActionPerformed);

        confirmPasswordCb.setText("show");
        confirmPasswordCb.addActionListener(this::confirmPasswordCbActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newPasswordCb))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oldPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oldPasswordCb))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(confirmPasswordCb))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(68, 68, 68)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(oldPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPasswordCb))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newPasswordCb)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(confirmPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confirmPasswordCb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(resetBtn)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        String enteredNewPassword = new String(newPasswordTf.getPassword());
        String enteredConfirmPassword = new String(confirmPasswordTf.getPassword());
        if (!enteredNewPassword.equals(enteredConfirmPassword)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "New password and confirmation do not match.", "Reset Password Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        oldPassword = new String(oldPasswordTf.getPassword());
        newPassword = enteredNewPassword;
        confirmPassword = enteredConfirmPassword;
        submitted = true;
        dispose();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void oldPasswordCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordCbActionPerformed
        // Echo char 0 shows the password; the normal echo char hides it again.
        oldPasswordTf.setEchoChar(oldPasswordCb.isSelected() ? (char) 0 : '*');
    }//GEN-LAST:event_oldPasswordCbActionPerformed

    private void newPasswordCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordCbActionPerformed
        // Echo char 0 shows the password; the normal echo char hides it again.
        newPasswordTf.setEchoChar(newPasswordCb.isSelected() ? (char) 0 : '*');
    }//GEN-LAST:event_newPasswordCbActionPerformed

    private void confirmPasswordCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordCbActionPerformed
        // Echo char 0 shows the password; the normal echo char hides it again.
        confirmPasswordTf.setEchoChar(confirmPasswordCb.isSelected() ? (char) 0 : '*');
    }//GEN-LAST:event_confirmPasswordCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ResetPassword dialog = new ResetPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox confirmPasswordCb;
    private javax.swing.JPasswordField confirmPasswordTf;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JCheckBox newPasswordCb;
    private javax.swing.JPasswordField newPasswordTf;
    private javax.swing.JCheckBox oldPasswordCb;
    private javax.swing.JPasswordField oldPasswordTf;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
