/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms.DoctorForm;

import Operations.DoctorOperation.DoctorOperation;
import Tools.HospitalEntityAllocator;
import entities.BaseEntity.AppointmentToFile;
import entities.BaseEntity.AssessmentTypeToFile;
import entities.BaseEntity.BaseEntity;
import entities.BaseEntity.Users.PatientToFile;
import entities.BaseEntity.Users.UserWithDetails;
import entities.BusinessEntity.Appointment;
import entities.BusinessEntity.Doctor;
import entities.BusinessEntity.AssessmentType;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class DoctorPanel extends javax.swing.JPanel {

    private HospitalEntityAllocator allocator;
    private Doctor doctor;
    private DoctorOperation doctorOperation;

    public DoctorPanel(HospitalEntityAllocator allocator, Doctor doctor) {
        initComponents();

        this.allocator = allocator;
        this.doctor = doctor;
        this.doctorOperation = new DoctorOperation(allocator, doctor);

        // =========================
        // Patient Consultation
        // =========================
        loadPatientList();
        loadAppointmentTable();

        patientComboBox.addActionListener(e -> {

            Object selectedItem
                    = patientComboBox.getSelectedItem();

            if (selectedItem == null) {
                appointmentComboBox.removeAllItems();
                return;
            }

            String patientId
                    = selectedItem.toString().split(" - ")[0];

            loadConsultationAppointmentList(patientId);
        });

        if (patientComboBox.getSelectedItem() != null) {

            String patientId
                    = patientComboBox.getSelectedItem()
                            .toString()
                            .split(" - ")[0];

            loadConsultationAppointmentList(patientId);
        }

        // =========================
        // Prescription
        // =========================
        loadPrescriptionPatientList();

        prescriptionPatientComboBox.addActionListener(e -> {

            Object selectedItem
                    = prescriptionPatientComboBox.getSelectedItem();

            if (selectedItem == null) {
                appointmentPrescriptionComboBox.removeAllItems();
                return;
            }

            String patientId
                    = selectedItem.toString().split(" - ")[0];

            loadPrescriptionAppointmentList(patientId);
        });

        if (prescriptionPatientComboBox.getSelectedItem() != null) {

            String patientId
                    = prescriptionPatientComboBox.getSelectedItem()
                            .toString()
                            .split(" - ")[0];

            loadPrescriptionAppointmentList(patientId);
        }

        // =========================
        // Medical Request
        // =========================
        loadRequestPatientList();

        requestPatientComboBox.addActionListener(e -> {

            Object selectedItem
                    = requestPatientComboBox.getSelectedItem();

            if (selectedItem == null) {
                appointmentRequestComboBox.removeAllItems();
                return;
            }

            String patientId
                    = selectedItem.toString().split(" - ")[0];

            loadRequestAppointmentList(patientId);
        });

        if (requestPatientComboBox.getSelectedItem() != null) {

            String patientId
                    = requestPatientComboBox.getSelectedItem()
                            .toString()
                            .split(" - ")[0];

            loadRequestAppointmentList(patientId);
        }

        loadAssessmentTypeList();

        doctorIdField.setText(doctor.getSelf().getId());
        nameField.setText(doctor.getSelf().getName());
        passwordField.setText(doctor.getSelf().getPassword());
        genderBox.setSelectedItem(doctor.getSelf().getGender().name());
        dobField.setText(doctor.getSelf().getDateOfBirth().toString());
        emailField.setText(doctor.getSelf().getEmail());
        phoneField.setText(doctor.getSelf().getPhoneNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doctorIdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        genderBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        temperatureField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        heartRateField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        systolicPressureField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        diastolicPressureField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        diagnosisField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultationNoteArea = new javax.swing.JTextArea();
        saveConsultationButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        patientComboBox = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        appointmentComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        medicationNameField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        dosageField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        frequencyField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructionsArea = new javax.swing.JTextArea();
        issuePrescriptionButton = new javax.swing.JButton();
        prescriptionPatientComboBox = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        appointmentPrescriptionComboBox = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        requestTypeBox = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        requestRemarkArea = new javax.swing.JTextArea();
        submitRequestButton = new javax.swing.JButton();
        requestPatientComboBox = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        appointmentRequestComboBox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        newStatusBox = new javax.swing.JComboBox<>();
        updateStatusButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Doctor ID: ");

        doctorIdField.setEditable(false);

        jLabel2.setText("Name: ");

        nameField.addActionListener(this::nameFieldActionPerformed);

        jLabel3.setText("Password: ");

        passwordField.addActionListener(this::passwordFieldActionPerformed);

        jLabel4.setText("Gender: ");

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "UNKNOWN" }));

        jLabel5.setText("Date of Birth: ");

        dobField.addActionListener(this::dobFieldActionPerformed);

        jLabel6.setText("Email:");

        emailField.addActionListener(this::emailFieldActionPerformed);

        jLabel7.setText("Phone Number:");

        saveButton.setText("Save Changes");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Personal Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailField)
                            .addComponent(dobField)
                            .addComponent(nameField)
                            .addComponent(doctorIdField)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(doctorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Profile", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setText("Patient: ");

        jLabel10.setText("Temperature:");

        jLabel11.setText("Heart Rate: ");

        jLabel12.setText("Systolic Pressure:");

        jLabel13.setText("Diastolic Pressure:");

        jLabel14.setText("Diagnosis:");

        diagnosisField.addActionListener(this::diagnosisFieldActionPerformed);

        jLabel15.setText("Consultation Note:");

        consultationNoteArea.setColumns(20);
        consultationNoteArea.setRows(5);
        jScrollPane1.setViewportView(consultationNoteArea);

        saveConsultationButton.setText("Save Consultation");
        saveConsultationButton.addActionListener(this::saveConsultationButtonActionPerformed);

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setText("Patient Consultation");

        patientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel29.setText("Appoinment:");

        appointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel29))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(patientComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(temperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(heartRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(systolicPressureField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(diagnosisField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(diastolicPressureField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(appointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(saveConsultationButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel16)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(appointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(temperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(heartRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(systolicPressureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(diastolicPressureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(diagnosisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveConsultationButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patient Consultation", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel17.setText("Prescription");

        jLabel19.setText("Medication Name:");

        jLabel20.setText("Dosage:");

        dosageField.addActionListener(this::dosageFieldActionPerformed);

        jLabel21.setText("Frequency:");

        jLabel22.setText("Duration (Days): ");

        jLabel23.setText("Instructions:");

        instructionsArea.setColumns(20);
        instructionsArea.setRows(5);
        jScrollPane2.setViewportView(instructionsArea);

        issuePrescriptionButton.setText("Issue Prescription");
        issuePrescriptionButton.addActionListener(this::issuePrescriptionButtonActionPerformed);

        prescriptionPatientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        prescriptionPatientComboBox.addActionListener(this::prescriptionPatientComboBoxActionPerformed);

        jLabel30.setText("Appointment:");

        appointmentPrescriptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel32.setText("Patient ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(372, 372, 372)
                            .addComponent(jLabel17))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(231, 231, 231)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel30)
                                        .addComponent(jLabel32))
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(prescriptionPatientComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(durationField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(frequencyField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dosageField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(medicationNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(appointmentPrescriptionComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(292, 292, 292))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(issuePrescriptionButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prescriptionPatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentPrescriptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(issuePrescriptionButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prescription", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel24.setText("Medical Request");

        jLabel25.setText("Patient ID:");

        jLabel26.setText("Assessment Type:");

        requestTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lab Test", "X-Ray", "Specialized Imaging" }));

        jLabel27.setText("Remark:");

        requestRemarkArea.setColumns(20);
        requestRemarkArea.setRows(5);
        jScrollPane3.setViewportView(requestRemarkArea);

        submitRequestButton.setText("Submit Request");
        submitRequestButton.addActionListener(this::submitRequestButtonActionPerformed);

        requestPatientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        requestPatientComboBox.addActionListener(this::requestPatientComboBoxActionPerformed);

        jLabel31.setText("Appointment:");

        appointmentRequestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requestTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestPatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentRequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(208, 208, 208))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(submitRequestButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(requestPatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(appointmentRequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(requestTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitRequestButton)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Medical Request", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel28.setText("Appointment Management");

        jLabel33.setText("New Status:");

        newStatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPLETED", "CANCELLED" }));

        updateStatusButton.setText("Update Status");
        updateStatusButton.addActionListener(this::updateStatusButtonActionPerformed);

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient", "Appointment Time", "Status"
            }
        ));
        jScrollPane4.setViewportView(appointmentTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(112, 112, 112))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(newStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(updateStatusButton)
                                .addGap(59, 59, 59)))
                        .addGap(114, 114, 114)))
                .addGap(176, 176, 176))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(updateStatusButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Appointment Management", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadAppointmentTable() {
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();

        model.setRowCount(0);

        List<AppointmentToFile> appointments = doctorOperation.getMyAppointments();

        for (AppointmentToFile appointment : appointments) {
            Appointment appointmentBusiness = allocator.getBusinessEntity(appointment.getId());

            PatientToFile patient = appointmentBusiness.getPatient();

            model.addRow(new Object[]{
                appointment.getId(),
                patient.getId() + " - " + patient.getName(),
                appointment.getAppointmentTime(),
                appointment.getStatus()
            });
        }
    }

    private void loadPrescriptionPatientList() {
        prescriptionPatientComboBox.removeAllItems();

        List<PatientToFile> patients = doctorOperation.getMyPatients();

        for (PatientToFile patient : patients) {
            prescriptionPatientComboBox.addItem(
                    patient.getId() + " - " + patient.getName()
            );
        }
    }

    private void loadPrescriptionAppointmentList(String patientId) {
        appointmentPrescriptionComboBox.removeAllItems();

        List<AppointmentToFile> appointments
                = doctorOperation.getMyAppointments();

        for (AppointmentToFile appointment : appointments) {

            if (appointment.getStatus()
                    != AppointmentToFile.AppointmentStatus.COMPLETED) {
                continue;
            }

            Appointment appointmentBusiness
                    = allocator.getBusinessEntity(
                            appointment.getId()
                    );

            PatientToFile patient
                    = appointmentBusiness.getPatient();

            if (!patient.getId().equals(patientId)) {
                continue;
            }

            appointmentPrescriptionComboBox.addItem(
                    appointment.getId()
                    + " - "
                    + appointment.getAppointmentTime().toLocalDate()
                    + " - "
                    + appointment.getStatus()
            );
        }
    }

    private void loadRequestPatientList() {
        requestPatientComboBox.removeAllItems();

        List<PatientToFile> patients = doctorOperation.getMyPatients();

        for (PatientToFile patient : patients) {
            requestPatientComboBox.addItem(
                    patient.getId() + " - " + patient.getName()
            );
        }
    }

    private void loadRequestAppointmentList(String patientId) {
        appointmentRequestComboBox.removeAllItems();

        List<AppointmentToFile> appointments
                = doctorOperation.getMyAppointments();

        for (AppointmentToFile appointment : appointments) {

            if (appointment.getStatus()
                    != AppointmentToFile.AppointmentStatus.COMPLETED) {
                continue;
            }

            Appointment appointmentBusiness
                    = allocator.getBusinessEntity(
                            appointment.getId()
                    );

            PatientToFile patient
                    = appointmentBusiness.getPatient();

            if (!patient.getId().equals(patientId)) {
                continue;
            }

            appointmentRequestComboBox.addItem(
                    appointment.getId()
                    + " - "
                    + appointment.getAppointmentTime().toLocalDate()
                    + " - "
                    + appointment.getStatus()
            );
        }
    }

    private String getSelectedAppointmentId() {

        int selectedRow = appointmentTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select an appointment from the Appointment Management table."
            );
            return null;
        }

        return appointmentTable
                .getValueAt(selectedRow, 0)
                .toString();
    }

    private void loadAssessmentTypeList() {
        requestTypeBox.removeAllItems();

        for (Object entity
                : allocator.getAllBusinessEntities(
                        AssessmentTypeToFile.PREFIX
                )) {

            AssessmentType assessmentType
                    = (AssessmentType) entity;

            if (assessmentType.getSelf().getCategory()
                    == AssessmentTypeToFile.AssessmentCategory.GENERAL_CHECKUP) {
                continue;
            }

            requestTypeBox.addItem(
                    assessmentType.getSelf().getId()
                    + " - "
                    + assessmentType.getSelf().getName()
                    + " ("
                    + assessmentType.getSelf().getCategory()
                    + ")"
            );
        }
    }

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void diagnosisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisFieldActionPerformed

    private void loadPatientList() {
        patientComboBox.removeAllItems();

        List<PatientToFile> patients = doctorOperation.getMyPatients();

        for (PatientToFile patient : patients) {
            patientComboBox.addItem(
                    patient.getId() + " - " + patient.getName()
            );
        }
    }

    private void loadConsultationAppointmentList(String patientId) {
        appointmentComboBox.removeAllItems();

        List<AppointmentToFile> appointments
                = doctorOperation.getMyAppointments();

        for (AppointmentToFile appointment : appointments) {

            if (appointment.getStatus()
                    != AppointmentToFile.AppointmentStatus.COMPLETED) {
                continue;
            }

            Appointment appointmentBusiness
                    = allocator.getBusinessEntity(
                            appointment.getId()
                    );

            PatientToFile patient
                    = appointmentBusiness.getPatient();

            if (!patient.getId().equals(patientId)) {
                continue;
            }

            appointmentComboBox.addItem(
                    appointment.getId()
                    + " - "
                    + appointment.getAppointmentTime().toLocalDate()
                    + " - "
                    + appointment.getStatus()
            );
        }
    }


    private void saveConsultationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveConsultationButtonActionPerformed
        Object selectedItem = patientComboBox.getSelectedItem();

        if (selectedItem == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a patient."
            );
            return;
        }

        String selectedPatient
                = selectedItem.toString();

        String patientId
                = selectedPatient.split(" - ")[0];

        Object selectedAppointment
                = appointmentComboBox.getSelectedItem();

        if (selectedAppointment == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select an appointment."
            );
            return;
        }

        String appointmentId
                = selectedAppointment.toString()
                        .split(" - ")[0];

        try {
            double temperature = Double.parseDouble(temperatureField.getText().trim());

            int heartRate = Integer.parseInt(heartRateField.getText().trim());
            int systolicPressure = Integer.parseInt(systolicPressureField.getText().trim());
            int diastolicPressure = Integer.parseInt(diastolicPressureField.getText().trim());

            String diagnosis = diagnosisField.getText().trim();
            String consultationNote = consultationNoteArea.getText().trim();
            doctorOperation.saveConsultation(
                    patientId,
                    appointmentId,
                    temperature,
                    heartRate,
                    systolicPressure,
                    diastolicPressure,
                    diagnosis,
                    consultationNote
            );

            JOptionPane.showMessageDialog(this, "Consultation saved successfully.");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Please enter valid numbers for vital signs.", "Invalid Input", JOptionPane.ERROR_MESSAGE);

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Save Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveConsultationButtonActionPerformed

    private void dosageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosageFieldActionPerformed

    private void updateStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusButtonActionPerformed
        int selectedRow = appointmentTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment.");
            return;
        }

        String appointmentId = appointmentTable.getValueAt(selectedRow, 0).toString();
        String selectedStatus = newStatusBox.getSelectedItem().toString();

        AppointmentToFile.AppointmentStatus status = AppointmentToFile.AppointmentStatus.valueOf(selectedStatus);

        try {
            doctorOperation.updateAppointmentStatus(appointmentId, status);
            appointmentTable.setValueAt(status.name(),selectedRow,3);

            refreshAppointmentDropdowns();

            JOptionPane.showMessageDialog(this,"Appointment status updated successfully.");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,e.getMessage(),"Update Failed",javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_updateStatusButtonActionPerformed

    private void issuePrescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuePrescriptionButtonActionPerformed

        Object selectedItem = prescriptionPatientComboBox.getSelectedItem();

        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this, "Please select a patient.");
            return;
        }

        String selectedPatient = selectedItem.toString();
        String patientId = selectedPatient.split(" - ")[0];

        Object selectedAppointment
                = appointmentPrescriptionComboBox.getSelectedItem();

        if (selectedAppointment == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select an appointment."
            );
            return;
        }

        String appointmentId
                = selectedAppointment.toString()
                        .split(" - ")[0];

        try {
            String medicationName = medicationNameField.getText().trim();
            String dosage = dosageField.getText().trim();
            String frequency = frequencyField.getText().trim();
            int durationDays = Integer.parseInt(durationField.getText().trim());
            String instructions = instructionsArea.getText().trim();

            doctorOperation.savePrescription(
                    patientId,
                    appointmentId,
                    medicationName,
                    dosage,
                    frequency,
                    durationDays,
                    instructions
            );

            JOptionPane.showMessageDialog(this, "Prescription issued successfully.");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Duration days must be a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Prescription Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_issuePrescriptionButtonActionPerformed

    private void submitRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRequestButtonActionPerformed
        Object selectedItem
                = requestPatientComboBox.getSelectedItem();

        if (selectedItem == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a patient."
            );
            return;
        }

        String selectedPatient
                = selectedItem.toString();

        String patientId
                = selectedPatient.split(" - ")[0];

        Object selectedAppointment
                = appointmentRequestComboBox.getSelectedItem();

        if (selectedAppointment == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select an appointment."
            );
            return;
        }

        String appointmentId
                = selectedAppointment.toString()
                        .split(" - ")[0];

        Object selectedAssessment
                = requestTypeBox.getSelectedItem();

        if (selectedAssessment == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select an assessment type."
            );
            return;
        }

        String selectedAssessmentType
                = selectedAssessment.toString();

        String assessmentTypeId
                = selectedAssessmentType.split(" - ")[0];

        try {

            String remark
                    = requestRemarkArea.getText().trim();

            doctorOperation.sendMedicalRequest(
                    patientId,
                    appointmentId,
                    assessmentTypeId,
                    remark
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Medical request sent successfully."
            );

            requestRemarkArea.setText("");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Request Failed",
                    JOptionPane.ERROR_MESSAGE
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to send medical request.",
                    "Request Failed",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_submitRequestButtonActionPerformed


    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String name = nameField.getText().trim();

        String password
                = new String(passwordField.getPassword());

        UserWithDetails.Gender gender
                = UserWithDetails.Gender.valueOf(
                        genderBox.getSelectedItem().toString()
                );

        String dob = dobField.getText().trim();
        String email = emailField.getText().trim();
        String phone = phoneField.getText().trim();

        try {
            doctorOperation.updateProfile(
                    name,
                    password,
                    gender,
                    dob,
                    email,
                    phone
            );

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Profile updated successfully."
            );
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Update Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void refreshAppointmentDropdowns() {

        // Patient Consultation
        Object consultationPatient
                = patientComboBox.getSelectedItem();

        if (consultationPatient != null) {

            String patientId
                    = consultationPatient.toString()
                            .split(" - ")[0];

            loadConsultationAppointmentList(patientId);
        }

        // Prescription
        Object prescriptionPatient
                = prescriptionPatientComboBox.getSelectedItem();

        if (prescriptionPatient != null) {

            String patientId
                    = prescriptionPatient.toString()
                            .split(" - ")[0];

            loadPrescriptionAppointmentList(patientId);
        }

        // Medical Request
        Object requestPatient
                = requestPatientComboBox.getSelectedItem();

        if (requestPatient != null) {

            String patientId
                    = requestPatient.toString()
                            .split(" - ")[0];

            loadRequestAppointmentList(patientId);
        }
    }
    private void prescriptionPatientComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionPatientComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescriptionPatientComboBoxActionPerformed

    private void requestPatientComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPatientComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestPatientComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> appointmentComboBox;
    private javax.swing.JComboBox<String> appointmentPrescriptionComboBox;
    private javax.swing.JComboBox<String> appointmentRequestComboBox;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JTextArea consultationNoteArea;
    private javax.swing.JTextField diagnosisField;
    private javax.swing.JTextField diastolicPressureField;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField doctorIdField;
    private javax.swing.JTextField dosageField;
    private javax.swing.JTextField durationField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField frequencyField;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JTextField heartRateField;
    private javax.swing.JTextArea instructionsArea;
    private javax.swing.JButton issuePrescriptionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField medicationNameField;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> newStatusBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> patientComboBox;
    private javax.swing.JTextField phoneField;
    private javax.swing.JComboBox<String> prescriptionPatientComboBox;
    private javax.swing.JComboBox<String> requestPatientComboBox;
    private javax.swing.JTextArea requestRemarkArea;
    private javax.swing.JComboBox<String> requestTypeBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveConsultationButton;
    private javax.swing.JButton submitRequestButton;
    private javax.swing.JTextField systolicPressureField;
    private javax.swing.JTextField temperatureField;
    private javax.swing.JButton updateStatusButton;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        BaseEntity.setIdNumberWidth(4);

        HospitalEntityAllocator allocator
                = new HospitalEntityAllocator(
                        java.nio.file.Path.of("data/Linker"),
                        java.nio.file.Path.of("data/Entity")
                );

//        SwingUtilities.invokeLater(() -> {
//            try {
//                new DoctorPanel(
//                        allocator,
//                        allocator.getBusinessEntity("DT0001")
//                ).setVisible(true);
//            } catch (Exception e) {
//                throw new RuntimeException(e);
//            }
//        });
    }
}
